### ISSUE TITLE
Create PostCSS plugin

### ISSUE THREAD

**Issue by fregante** [bfred-it/object-fit-images#1]

**Comment by mshick** [comment]
@bfred-it I put together a simple postcss plugin here: https://github.com/ronik-design/postcss-object-fit-images

I pretty directly copied the mixin functionality into the plugin. It's very simple, but seems to work. Let me know if I can make any changes to better accommodate.

**Comment by fregante** [comment]
Awesome, thank you! I'll add a link to my readme soon =) 

Edit: Travis is disabled https://travis-ci.org/mshick/postcss-object-fit-images
