### ISSUE TITLE
Assignment to read-only properties is not allowed in strict mode

### ISSUE THREAD

**Issue by nicooprat** [bfred-it/object-fit-images#100]
Got this error on IE 11 (Windows 8): `Assignment to read-only properties is not allowed in strict mode` at this line: https://github.com/bfred-it/object-fit-images/blob/bd8a2d3111c089bbe750765865ff4082635f840d/dist/ofi.js#L171

Any way to fix this?

I'm using Webpack 2.4.1 to compile my bundle.

**Comment by fregante** [comment]
It works for me on IE11/Win8.1 both in [the demo](https://bfred-it.github.io/object-fit-images/demo/) (which loads the JS file directly in the browser) and one of my sites also built with webpack 3.8

Can you create the smallest possible bundle by requiring only object-fit-images? This is probably a build issue

**Comment by nicooprat** [comment]
@Seems to be working when building with production mode. Don't have time to investigate further for now... Thanks anyway.

**Edit: spoke too fast, it's back.**
