### ISSUE TITLE
How to use this in angular project?

### ISSUE THREAD

**Issue by dhiraj-paryani** [bfred-it/object-fit-images#107]
1) I added the "import 'object-fit-images/dist/ofi.min.js"; in my polyfill.ts.
2) Added the font-family: 'object-fit: contain;'; in css file.

Does this requires anything else?

**Comment by fregante** [comment]
The usage is the same for all https://github.com/bfred-it/object-fit-images#usage

**Comment by dhiraj-paryani** [comment]
@bfred-it, I did the same changes, Could you clarify the 3rd point in the usage.
Where do I need to add objectFitImages();??
