### ISSUE TITLE
PhantomJS - Attempting to change access mechanism for an unconfigurable property

### ISSUE THREAD

**Issue by luruke** [bfred-it/object-fit-images#11]
Hi there,
Seems that PhantomJs (well, most likely QtWebkit) doesn't like `.defineProperty` over an already existing property.

Do you foresee any easy way to make the script working without `.defineProperty`?
I assume this bug is also affecting old Safari versions.

example rendering:

``` javascript
var page = require('webpage').create();

page.open('http://bfred-it.github.io/object-fit-images/demo.html', function() {
  page.evaluate(function() {
    return document.querySelector('button').click();
  });

  global.setTimeout(function() {
    page.render('test.png');
    phantom.exit();
  }, 3000);
});
```

render:
![test](https://cloud.githubusercontent.com/assets/61326/14544900/ac86d5da-029b-11e6-9426-ba2e42225f6c.png)

UA:
![test](https://cloud.githubusercontent.com/assets/61326/14545070/84fae58c-029c-11e6-93db-fdf67dde8d82.png)

Cheers!

**Comment by fregante** [comment]
I'm not a fan of changing code to fix testing environments and I don't like to add cruft, so I can't do this. 

Also I'm using `defineProperty` instead of `img.src = "aaa.jpg"` because that has a completely different behavior. In short, I don't think there's another way to do it.
