### ISSUE TITLE
Test in IE with version 3.2.4

### ISSUE THREAD

**Issue by VisheshSingh** [bfred-it/object-fit-images#111]
I have followed the steps in readme and can't get it to work on IE. Here's what I did:
1. `<img src="my-image.jpg" class="myImg">`
2. `.myImg {object-fit: cover; font-family: 'object-fit: cover; object-position: bottom;';}`
3. In my JS, i am importing it this way:
```
import objectFitImages from 'object-fit-images';
objectFitImages(); 
```

**Comment by fregante** [comment]
Not a bug in the polyfill, the problem is elsewhere and it needs debugging
