### ISSUE TITLE
IE11: Including the polyfill in two different libraries via ES6 imports then including both onto the page breaks it

### ISSUE THREAD

**Issue by TimeDropsSB** [bfred-it/object-fit-images#112]
Similar issue as in #94.

I am currently using object-fit-images in two different libraries, imported via ES6 imports/CommonJS requires.  When both libraries are included on the same page, the polyfill no longer works correctly for one of the libraries.

In IE11, what happens when both libraries are included is that the `<img>` tags all contain a `background-image` property where its URL begins with `data:image/svg+xml`.  

A quick debug shows that the the second object-fit-images lib has logic problems after the first object-fit-images polyfills; the logic problem trickles and results the second lib to get locked into an infinite loop within `onImageReady()` because `img.naturalHeight` condition is never met; thus, the callback can never be executed. 

The obvious solution is to use a CDN and include as a `<script>` tag instead but this is a huge problem if it is used as an ES6 import.  Is there a way to fix this?

**Comment by fregante** [comment]
It’s a polyfill, it shouldn’t be imported automatically by other libraries, but just by the end user, once, before anything else runs.

**Comment by TimeDropsSB** [comment]
It's not imported automatically; I'm the one importing them because the libraries belong to me.  One of them is a Custom Element components library, the other is a React components library.  They are consumed by multiple higher level apps so the libs need to function independently.  

I guess I will just manually set it to the window object to use as a flag to check if it is set already.
