### ISSUE TITLE
Unable to use with Next

### ISSUE THREAD

**Issue by davidrhoderick** [bfred-it/object-fit-images#117]
I'm not sure if is an SSR issue or something else.  I'm on object-fit-images version 3.2.4 and when I follow the instructions and call `objectFitImages()` in the `MyApp` function, it doesn't do anything.  So I moved the call to `useEffect` so that it emulates `document.ready` and I get the following error that `objectFitImages` is not a function:

![image](https://user-images.githubusercontent.com/2300366/113323969-d9f1d400-9316-11eb-8958-17831a3b67c8.png)

Here's my code:
```
import objectFitImages from 'object-fit-images'

function MyApp({ Component, pageProps }) {
  useEffect(() => {
    objectFitImages()
  }, [])
  
  return <>
    <Navbar />
    <Component {...pageProps} />
  </>
}

export default MyApp
```
I also tried to move the `objectFitImages` calls to the pages that need them and it still didn't work (but I didn't try in `useEffect` there).

**Comment by fregante** [comment]
This is unrelated to next. The error just says it’s not a function, which means that something in the build or the way it’s imported is not right. I suggest searching existing issues for a possible solution.

**Comment by fregante** [comment]
You *might* have to use `require` to import the module
