### ISSUE TITLE
A request to have a de-initialization (cleanup) API

### ISSUE THREAD

**Issue by vittorius** [bfred-it/object-fit-images#118]
For projects that handle DOM load in their own way and cache/restore the `<body>` of every page upon navigation (e.g. using [Turbolinks](https://github.com/turbolinks/turbolinks)), there's a need for some kind of cleanup API that will restore the DOM to its initial state and remove any placeholders.

Then, the usage may look the following:

```javascript
const imgSelector = 'img'

document.addEventListener('turbolinks:load', () => {
  // No "auto mode": using the explicit selector
  // to avoid object-fit-images adding a 'load' event handler under the hood
  objectFitImages(imgSelector, { watchMQ: true })
})

document.addEventListener('turbolinks:before-cache', () => {
  objectFitImagesDestroy(imgSelector)
})
```

I've tried to implement such a cleanup on my own for my project but I was limited in time and haven't fully understood the relations between image clones and DOM placeholders.

It would be great to have such an API.

**Comment by fregante** [comment]
Sorry this package is not under active development. I think that `keepSrcUsable` makes it a little hard to undo it. It's best you just replace them, for example (but using real DOM APIs to recreate the element):

```js
document.addEventListener('turbolinks:before-cache', () => {
  document.querySelectorAll(imgSelector).forEach(image => {
    image.replaceWith(<img src={image.src} width={image.width} height={image.height}/>)
  })
})

**Comment by vittorius** [comment]
Thanks for the workaround.
