### ISSUE TITLE
Getting this to work

### ISSUE THREAD

**Issue by djmtype** [bfred-it/object-fit-images#12]
I've read the docs, but still can't get this to work for IE9. In order to get `object-fit:cover` to work normally, a height and width of 100% needs to be declared. In IE9, it just distorts. Am I missing something?

```
<html>
<head>
<script src="ofi.browser.js"></script>
<script>objectFitImages();</script> 

<style>
img.my-image {
object-fit: cover;
height: 100%;
width: 100%;
font-family: 'object-fit: cover';
}
</style>
</head>
<body>
<img class="my-image" src="image.jpg" alt="" />
</body>
</html>
```

**Comment by fregante** [comment]
You might have to run that on DOM ready or simply at the bottom of the document. I should probably add that to the readme
