### ISSUE TITLE
Won't work with lazy loaded images

### ISSUE THREAD

**Issue by lucadegasperi** [bfred-it/object-fit-images#13]
Hello,
I want to use this polifill together with https://github.com/aFarkas/lazysizes which I use to lazy load images and https://github.com/scottjehl/picturefill for the srcset polyfill.
My yes case is the following: I have a carousel with a srcset on the img tag. By default every image in the carousel has an inline placeholder image (base64 gif) The first image in the carousel loads correctly and this library does the job fine. For all the other images in the carousel I get the placeholder images instead.

**Comment by fregante** [comment]
Can you create a demo on codepen or similar that I can work on?

**Comment by lucadegasperi** [comment]
you can see the problem in action (I was using IE11) here: https://www.victorcanera.com/diamonds/xpaamk-2.014-e-vs1-ideal-estimated-old-european-cut
The carousel images after the first one aren't loaded correctly (instead the placeholder image is used)

**Comment by bfred-it** [comment]
I can't work on your website to fix the issue though, I'd need a *reduced test case*

**Comment by brettburwell** [comment]
@lucadegasperi: It looks like Lazysizes recently added support for `object-fit`. Check [it out here](https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/object-fit). I realize this is an old thread but I thought I'd pass it along in case it's useful.

**Comment by lucadegasperi** [comment]
Thanks for letting me know :)

**Comment by terryupton** [comment]
@lucadegasperi were you able to implement this? I have not been able to resolve...I can get the polyfill to work but not for lazyload images, only the first image. I have tried to use the support plugins in lazysizes but either I am not using correctly or it doesn't resolve this issue.
