### ISSUE TITLE
<video> support?

### ISSUE THREAD

**Issue by albell** [bfred-it/object-fit-images#20]
Hey Federico, nice work, keep it up!

I wanted to inquire about `<video>` support. I have an immediate need for this, and will probably be using Fitie. I realize it's more code, and a wrapper element and you're trying to keep things lean. If video could be supported via an add-on module that would be useful. Thanks for considering.

**Comment by fregante** [comment]
The behavior is entirely different and not adaptable so if you need video you'll have to use fitie. Or use fitie as an add-on (both are pretty lightweight) for `<video>` and object-fit-images for the `<img>`
