### ISSUE TITLE
Demo broken in IE11

### ISSUE THREAD

**Issue by tannerhodges** [bfred-it/object-fit-images#22]
Testing in IE11 on Windows 7 in BrowserStack. Haven't taken a hard look yet, but the debugger's saying `s["object-fit"]` is returning null.

Here's some quick screenshots and [a screencast](https://www.dropbox.com/s/lahvddnxy9jwnrm/2016-05-26%20screencast.mp4?dl=0):

![Screenshot from BrowserStack](https://cloud.githubusercontent.com/assets/1619485/15592238/1502ec9e-2370-11e6-8335-65e5a124cdb3.png)

![Screenshot from BrowserStack - Error](https://cloud.githubusercontent.com/assets/1619485/15592392/5b27e2c8-2371-11e6-852f-866f677e74e6.png)

**Comment by fregante** [comment]
Thank you! I'll fix it soon, I think it's because it's being applied to an image without object-fit. The error shouldn't happen though

**Comment by fregante** [comment]
Should be fixed now :)

**Comment by tannerhodges** [comment]
Awesome, looks good. Thanks for the quick response.
