### ISSUE TITLE
Bower package

### ISSUE THREAD

**Issue by sergiop** [bfred-it/object-fit-images#23]
Beautiful script, please add bower package!

**Comment by fregante** [comment]
If you have bower you also have npm, just use `npm install` and you'll have one less dependency (bower)

https://www.quora.com/Why-use-Bower-when-there-is-npm

**Comment by sergiop** [comment]
In general, I can even agree with you, but many people use bower and they do not want to reconfigure their stack with browserify. For example, I use Sage as Wordpress Starter Theme ([https://roots.io/sage/](https://roots.io/sage/)) and all project components are installed and configured with bower.
You may also not agree with the use of bower, but why put limits on who use it? I ask you to reconsider your position. Thanks.

**Comment by fregante** [comment]
Because I would be the one who has to support that. 

There are alternative solutions, this is one of many: http://www.leveluplunch.com/blog/2014/05/20/bower-install-from-github-stash-repository-url/

**Comment by sergiop** [comment]
I hope you don't mind if I tell you that you're a little bit extremist in your positions! :-)
Thanks for the support, and I'm sorry for my disappointment, your project is stil great even without bower support.

**Comment by samburgers** [comment]
+1
