### ISSUE TITLE
object-fit: scale-down doesn't work with SVG images in IE

### ISSUE THREAD

**Issue by aaronjpitts** [bfred-it/object-fit-images#24]
Hi,

Great plugin but I've noticed it doesn't properly render SVG images using object-fit: scale-down in IE 11. I've not tested Edge or other version of IE.

Would you be able to support this?

Thanks!

**Comment by bfred-it** [comment]
It should work regardless of the format if you're using the `img` tag

**Comment by fregante** [comment]
If you're using the `img` tag, it should work regardless of the format. I just tested IE11

If you're using the `svg` tag, you don't need `object-fit` but the `viewBox` attribute and perhaps `preserveAspectRatio`, but that can't replicate `scale-down` without Javascript

[More info about `viewBox` and `preserveAspectRatio`](https://sarasoueidan.com/blog/svg-coordinate-systems/#preserveAspectRatio-syntax)
