### ISSUE TITLE
Not working with charset="ISO-8859-1"

### ISSUE THREAD

**Issue by hadarweiss** [bfred-it/object-fit-images#25]
Hi,
I want to use the polyfill inside a website with charset="ISO-8859-1" meta tag at the document head, but I can't because of the special char you are using for the variable in row 3.
This is the error I get: Uncaught SyntaxError: Unexpected token ILLEGAL (ofi.common-js.js:3).

**Comment by fregante** [comment]
Once you minify it should work. Alternatively you can require the already-minified file in version 2.5.3 (just published)

``` js
require('object-fit-images/dist/ofi.browser.js')
```
