### ISSUE TITLE
Unable to get property ... of undefined or null reference

### ISSUE THREAD

**Issue by MalikDrako** [bfred-it/object-fit-images#26]
In IE11, I'm getting `Unable to get property 'data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==' of undefined or null reference`
on this section:
`for (var n = 0; n < e.length; n++) {
            e[n][t] = e[n][t] || r; /* n is 0, e[n] is undefined, t is 'data:image...' */
            u(e[n]);
        }`

I include it as `<script type="text/javascript" src="http://mysite.dev/wp-content/themes/mytheme/js/ofi.browser.js?ver=20160603"></script>`
and call it as `jQuery(objectFitImages);`

**Comment by fregante** [comment]
There was an issue in the documentation. This is the correct way to call it if you're using jQuery:

``` js
$(function(){
    objectFitImages();
});
```
