### ISSUE TITLE
scale-down doesn't work if the images are shown on hover

### ISSUE THREAD

**Issue by aaronjpitts** [bfred-it/object-fit-images#27]
Hi,

Please check out my example site at: http://185.48.144.115 in the menu at the top hover over the 'services' link to see the submenu in Safari. It doesn't seem to calculate the images correctly if they are in a hidden element on page load. Any way to work around this? I haven't tested this in IE. I need to use it in Safari for the object-position support.

Thank you

**Comment by bfred-it** [comment]
The site is not loading

**Comment by fregante** [comment]
`scale-down` needs the element to be visible when you run `objectFitImages()`

You have to run it when it's open:

``` js
$('.nav-menu__item').on('mouseenter', function () {
  objectFitImages($('img', this));
})
```

or just use use `contain` (which in your case should work just fine)

**Comment by aaronjpitts** [comment]
Thank you for the suggestion above. It's better, but in safari it's positioning the images to the right when i want object-position: left, in IE the images are too skewed: http://185.48.144.115

Do you have any other suggestions?

Thank you
