### ISSUE TITLE
iOS 7 Safari - "TypeError: Attempting to change access mechanism for an unconfigurable property."

### ISSUE THREAD

**Issue by IainAndrew** [bfred-it/object-fit-images#30]
Thanks for the great polyfill. On iOS 7 I'm getting this error:
"TypeError: Attempting to change access mechanism for an unconfigurable property." referring to this line https://github.com/bfred-it/object-fit-images/blob/ae51239cd762d83dc444e817cac6d675015cefdd/index.js#L151

Any idea what is causing this?

**Comment by fregante** [comment]
I could probably fix the error but you wouldn't be able to read and set the `<img>`'s `src` property. Would that work for you?

**Comment by IainAndrew** [comment]
Probably not in this case, as I'm using [lazysizes](https://github.com/aFarkas/lazysizes) to lazyload the images.

**Comment by fregante** [comment]
Then probably this can't work for you, at least not in iOS 7. Overwriting that property is necessary to keep the `<img>` working.

Edit: I looked into this further and I'm confirming that there's no way to fix this, considering that to make it possible in node somebody had to load a `C` extension https://github.com/qix-/node-force-delete (which is node-only)
