### ISSUE TITLE
Typeerror

### ISSUE THREAD

**Issue by vincecarney** [bfred-it/object-fit-images#32]
Page loads and after script runs, image disappears.

Console error - ofi.browser.js:
**Typeerror: attempting to change access mechanism for an unconfigurable property**

Ipad Mini 2
OS: iOS v7
Browser: Safari

**Comment by vincecarney** [comment]
I'm able to replicate the image disappearing on the following devices:

Ipad 4 - iOS v7 - Safari
Ipad Air - iOS v7 - Safari
iPhone 5s - iOS v7 - Safari
iPhone 5 - iOS v6 - Safari
Windows 8.1 - Safari 5.1

Any thoughts?

**Comment by fregante** [comment]
Yes, it's not compatible with iOS 7

I can add compatibility but you won't be able to change or read the `src` property

**Comment by vincecarney** [comment]
Is it possible to try/catch so as to not break sites when viewing with
these devices?

**Comment by bfred-it** [comment]
> I can add compatibility but you won't be able to change or read the `src` property

**Comment by bfred-it** [comment]
Also don't use Safari for Windows, it's 4 years old and unsupported by Apple themselves.

**Comment by vincecarney** [comment]
Is it possible to disable the script on unsupported devices so images are
still visible?

**Comment by bfred-it** [comment]
The script doesn't automatically apply, so you can use a condition to avoid applying it in safari 7:

```js
if(!isSafari7orLess) objectFitImages()

**Comment by vincecarney** [comment]
I'd prefer not to mess with browser sniffing. I haven't looked at the code... but would it be possible to rely on feature detection instead. When objectFitImages() gets called, images disappear for the devices I noted above.

**Comment by fregante** [comment]
This is now fixed, the polyfill is applied correctly but you won't be able to read the correct `src` value via javascript. For example:

``` html
<img src="image.jpg">
```

``` js
objectFitImages();
console.log(document.querySelector('img').src);
// in semi-modern browsers: http://example.com/image.jpg
// in iOS7: data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==
```

<img width="254" alt="ios 7 screenshot" src="https://cloud.githubusercontent.com/assets/1402241/17430702/b51f1362-5aaa-11e6-9f61-5b3ed69e8999.png">
