### ISSUE TITLE
Fix makes image larger than it should be

### ISSUE THREAD

**Issue by thijsvandien** [bfred-it/object-fit-images#34]
I have a two column layout with text on the left and an image on the right. The image is supposed to cover the whole second column, which should be as tall as it needs to be to fit the text. In browsers with native support for object-fit this works fine, but when I apply OFI, the image becomes taller than it needs to be. As a result, the text column gets additional space at the bottom that it shouldn't have and the image gets cropped more than necessary. See https://jsfiddle.net/ynrsmoaa/.

**Comment by fregante** [comment]
`object-fit` requires the height and width to be defined. If you leave it to the browser (`height: auto`) it's going to use the image's height, which in this case is 667px. 

To avoid issues with responsiveness, OFI doesn't force that size, but the solution would be to simply avoid `height: auto` (which doesn't do anything coupled with flexbox anyway) https://jsfiddle.net/ynrsmoaa/2/

**Comment by thijsvandien** [comment]
The `height: auto` did serve a purpose; it caused the image to be as tall as the text column next to it, which is exactly what I want. OFI broke that. Please compare our links in Firefox to see that now they don't behave the same even without OFI. Safari shows how OFI makes it go wrong. With `height: auto` and without OFI the image has the correct height but wrong position; with OFI the position is correct but the height isn't anymore.

**Comment by thijsvandien** [comment]
I will add that I did find a way to make it work, using `position: absolute`. The main downside I can think of is that in older browsers, which will not support `object-fit` even with this polyfill, the image will lose its proportions – I would prefer whitespace then. There might be other cases where this solution can't be applied, so if it can't be fixed, it might at least be documented (if only be means of this issue). See https://jsfiddle.net/ynrsmoaa/3/.

**Comment by fregante** [comment]
The behavior you're describing is not consistent across the browsers even without OFI. This is how your first link appears in Firefox, Safari and Chrome (broken one)

![firefox](https://cloud.githubusercontent.com/assets/1402241/18440964/f0229636-78bf-11e6-915b-d2696b655a8a.png)
![safari](https://cloud.githubusercontent.com/assets/1402241/18440965/f032bc50-78bf-11e6-852f-06e0cdc2dc1a.png)
![chrome](https://cloud.githubusercontent.com/assets/1402241/18440966/f06c7c38-78bf-11e6-909f-47d39e41501a.png)

If you find a solution to that _maybe_ we can look into making OFI play nice.
