### ISSUE TITLE
Breaking other js functions

### ISSUE THREAD

**Issue by anartfulscience** [bfred-it/object-fit-images#39]
Hello,

Great script!

Is there anyway of delivering for IE only? It seems to be breaking other scripts I have running on the page.

Thanks, Stephen

**Comment by fregante** [comment]
What scripts is it breaking? It can't break anything since it already doesn't run unless it's necessary.

**Comment by anartfulscience** [comment]
[ob.txt](https://github.com/bfred-it/object-fit-images/files/504393/ob.txt)

Hello,

Thanks for the quick response!.

I've a few functions working on the page. Activating accordions and toggles. The issue is intermittent and seems to be on Chrome but as soon as I remove the attached everything works. 

I'm not sure why?

Cheers, Stephen

**Comment by fregante** [comment]
I'm not either. Show what exactly breaks and any errors in the console; "it doesn't work" is never enough to figure out why https://ericlippert.com/2014/03/05/how-to-debug-small-programs/
