### ISSUE TITLE
Internet Explorer No-Go

### ISSUE THREAD

**Issue by djmtype** [bfred-it/object-fit-images#40]
View the [demo](http://bfred-it.github.io/object-fit-images/demo/) in IE9 or IE11 and you can clearly see it does not work unfortunately. [Screenshot](https://cloudup.com/crHs-h6JNQn)

**Comment by fregante** [comment]
It does here! Any errors in the console?

<img width="947" alt="IE11" src="https://cloud.githubusercontent.com/assets/1402241/19043890/d2b4fc0a-8946-11e6-8795-93bdecd3d995.png">

**Comment by fregante** [comment]
Also IE9

<img width="382" alt="ie9" src="https://cloud.githubusercontent.com/assets/1402241/19043971/277c4f9a-8947-11e6-934b-ea3e05a23654.png">

**Comment by djmtype** [comment]
Please can understand my skepticism since there are no JS errors and all resources are loaded. I am running Windows 7 on Virtual Box, with an unmodified disc image downloaded from https://modern.ie. It's pretty unusual, your remote demo works for you, and not here. I don't have any special firewall or conditions setup that would be blocking the demo url.
[https://cloudup.com/cOCFMsFSxrt](https://cloudup.com/cOCFMsFSxrt)

**Comment by djmtype** [comment]
Sorry, I totally missed the call-to-action button _Apply Fix_. My bad.
