### ISSUE TITLE
breaks in IE if element is not present

### ISSUE THREAD

**Issue by developer-lindner** [bfred-it/object-fit-images#41]
If passed selector is not present in DOM, ofi triggers an error which stops execution of js in IE.
Documentation should give an advice here or maybe handle it inside ofi.

**Comment by fregante** [comment]
That doesn't seem to be the case. What error are you getting?

http://jsbin.com/tulohixowa/1/edit?html,js,output

<img width="814" alt="ofi on detached elements in IE11" src="https://cloud.githubusercontent.com/assets/1402241/19107475/4930f4dc-8aa1-11e6-913d-d51ee5141413.png">

**Comment by fregante** [comment]
Or, if you pass an actual selector that doesn't match anything: http://jsbin.com/revowixide/1/edit?html,js,console

**Comment by developer-lindner** [comment]
Well, we just encountered that issue in IE9 / 10 using:

`objectFitImages( $('.image-container img') );`

**Comment by fregante** [comment]
This works for me: http://jsbin.com/dimenerica/1/edit?css,js,output

You can also use `objectFitImages('.image-container img');` — no need for jQuery.

Include the exact error you're getting when you report an issue.
