### ISSUE TITLE
Non minified code in Github

### ISSUE THREAD

**Issue by GuillaumeGBzh** [bfred-it/object-fit-images#48]
Hello,

I have a problem when I include the library in my Gulp workflow.
"Uglify" removes a function from your code.

Can you added the non minified code in Github?

Thank you

**Comment by fregante** [comment]
Refer to https://github.com/bfred-it/object-fit-images/issues/37#issuecomment-255364967

In short, **update gulp-uglify** to v2, it's a uglify bug that it's avoided in newer versions
