### ISSUE TITLE
Cannot use jQuery object as parameter

### ISSUE THREAD

**Issue by josefTrojanINSPIREcz** [bfred-it/object-fit-images#51]
Hi. I cannot use jQuery object as parameter of function objectFitImages(), like you have written down in your example in documentation:
`// or with jQuery`
`var $someImages = $('img.some-image');`
`objectFitImages($someImages);`

JS error in console shows up. I have tested it in your DEMO. I have tried a different versions of jQuery, not helped. Thanx.

**Comment by fregante** [comment]
I'm not sure of why it wouldn't work. Try this in the meanwhile:

```js
var $someImages = $('img.some-image');
objectFitImages($someImages.get());
```

**Comment by josefTrojanINSPIREcz** [comment]
Unfortunately, it doesn´t work. The 'unknown error' shows only IE. In other browsers, it shows no errors, but the script doesn´t work anyway.

**Comment by fregante** [comment]
What about skipping jQuery altogether?

```js
objectFitImages('img.some-image');
```

I don't have much time to look into it now :(

**Comment by fregante** [comment]
This works for me: http://jsbin.com/dovajoxere/1/edit?html,css,js,output
