### ISSUE TITLE
jQuery.clone() before load on IE result in transparent

### ISSUE THREAD

**Issue by the-felis-leo** [bfred-it/object-fit-images#53]
Running on IE11.

on document ready, I call objectFitImages().
I have a carousel that do a jQuery clone() to have enought card to cycle.

But cloned image have the transparent data:image/gif;base64 as src and background,
instead of the expected image.

Original images fit as expected.

I find that bug seem occurs when image are not allready load,
and workraround with   $(document).ready(function ($) {    setTimeout(objectFitImages, 500);     });

**Comment by fregante** [comment]
`ofi` works by replacing the image with a transparent one and setting the original as a CSS background. This cannot be _fixed._

After using `.clone()` you'll have to re-set the real `src`, like:

```js
var $originals = $('img.you-want-to-clone');
var $clones = $originals.clone().map(function (i) {
  this.src = $originals[i].src;
});
```

This works because the `ofi` tries to [preserve the original `src`](https://github.com/bfred-it/object-fit-images/blob/f8e94305a840e3fa0bd404adb59b2d5515de7e69/index.js#L161-L166) when accessing it directly, but can't do anything when `.clone()` is run.

---

Alternatively, if possible, clone them _before_ running `objectFitImages(...)`

**Comment by the-felis-leo** [comment]
Thanks !  It works.

But not very happy, because this's coupling other library with ofi.

I propose you a patch to handle cloned element :

	function fixOne(el, requestedSrc) {

		...

		// store info on object for later use
		if (el[ಠ].s) {
			...
		} else {
			/// --- PATCH BEGIN ---
			if (src === ಠ) {
				var bgimg = (el.style.backgroundImage || '').trim();
				var defurl = 'url("' + src + '")';
				if (  (bgimg != defurl)
					&& (bgimg.indexOf('url(') == 0)
					&& (bgimg.lastIndexOf(')') == bgimg.length - 1)
					) {
					// Cloned patched element. Need to get original url.
					src = bgimg.substring(4, bgimg.length - 1);
				}
			}
			/// --- PATCH END ---
			el[ಠ] = { ... };
			el.src = ಠ;

			try {
				...
			}
		}

		...
	}

The test could be done better, by appending a custom attribute or class (like data-ofi-initial-src).

**Comment by fregante** [comment]
That's not a bad idea. Are you using ofi in auto mode? (i.e. `objectFitImages()` without any arguments)

**Comment by the-felis-leo** [comment]
Yes, I am.

**Comment by fregante** [comment]
This will be in 3.0.0, which I pushed as a pre-release version. Install it with this and let me know if it works for you:

```sh
npm install object-fit-images@next
```

I tested it with this on the demo page: 

```js
document.body.appendChild(document.querySelector('.OF-contain').cloneNode());
```
