### ISSUE TITLE
initial scale-down not applied if image not allready loaded on IE

### ISSUE THREAD

**Issue by the-felis-leo** [bfred-it/object-fit-images#58]
On IE 11.
Using scale-down.

On document ready, I call `objectFitImages(null, {watchMQ:true});`
But image scale-down only when I resize the widow a first time.

Workaround: do a second call on a timeout.
```
    $(document).ready(function ($) {
        // init OFI
        objectFitImages(null, {watchMQ:true});
        // need to be recalled after image loaded to apply first scale down
        setTimeout(objectFitImages, 700);
        setTimeout(objectFitImages, 1200);
        setTimeout(objectFitImages, 2000);
        setTimeout(objectFitImages, 3000);
        setTimeout(objectFitImages, 5000);
    });
```
It seems that objectFitImages need that images are allready loaded to apply the first scale down.

**Comment by fregante** [comment]
Which version are you using? 2.5.9 or 3.0.0-0?

Images indeed need to be partially loaded before scale-down is applied, but that should be taken care of by [this code](https://github.com/bfred-it/object-fit-images/blob/40b16969f27b8d2898a19c006ac29ba534af5828/index.js#L119)

**Comment by the-felis-leo** [comment]
I've not seen any embed number version, so I can't tell you.
But sure not the last 3.0.

Thank you, I will get that update.
