### ISSUE TITLE
Activate the plugin automatically without having to press the button

### ISSUE THREAD

**Issue by alvaro0022** [bfred-it/object-fit-images#61]
Hello;
Excellent contribution, I would like to know what to do to activate the plugin without having to press the button. The plugin is automatically activated when loading the pagian.

**Comment by fregante** [comment]
I haven't implemented this, but it's been on my mind. Perhaps it can be done via attribute on `<html>` (or anywhere else), like `<html class="OFI">`

Would that work?

**Comment by alvaro0022** [comment]
I'm not sure. I asked because I do not know about programming. I managed to work with the thumbnails of wodpress, it works great, but the problem is that you have to press the button to work.
`<button type="button" onclick="applyOFI()">Apply OFI</button>`
 sorry for my English

**Comment by fregante** [comment]
I understand now. You don't need the button, you only need to call `objectFitImages()` in JavaScript at some point. You can add this code to `functions.php`:

```php
<?php
function enableOFI() {?><script>objectFitImages()</script><?php}
add_action( 'wp_footer', 'enableOFI' );
```

**Comment by alvaro0022** [comment]
Incredible, works perfectly, thank you very much!
