### ISSUE TITLE
Edge / IE console error: Function Expected

### ISSUE THREAD

**Issue by damienmcd** [bfred-it/object-fit-images#62]
I'm seeing this error on Edge, IE11 and IE10.
Seeing 'Function Expected' in the console.
The CSS is implemented with the following:
```
.image {
  object-fit: cover;
  object-position: center;
  font-family: 'object-fit: cover; object-position: center;'
}
```

Calling Object Fit in JQuery as follows:
```
jQuery(function($) {
  objectFitImages();
});
```

**Comment by fregante** [comment]
The [demo](https://bfred-it.github.io/object-fit-images/demo/) works for me in IE 11. Can you post the full error you're seeing?

**Comment by damienmcd** [comment]
The full error in Edge is:
```
SCRIPT5002: Function Expected
main-min.js (68,5882)
```

I've updated the initial comment as I've narrowed down the other error that I was seeing but still seeing the issue with the "Function Expected" console error at the objectFitImages section of our main-min.js

**Comment by fregante** [comment]
I don't think the error is caused by OFI. Post the website that you're seeing this issue on so I can take a look.

Make sure you're loading OFI correctly. Are you using browserify? Webpack? How are you loading OFI?

**Comment by damienmcd** [comment]
I'm currently seeing the issue while testing a local build.
OFI is being prepended using CodeKit and being called within JQuery with
```
objectFitImages();
```

**Comment by fregante** [comment]
Try running 

```js
jQuery(function() {
    console.log(typeof objectFitImages);
});
```

What's its output in the console?

Which OFI file are you prepending? ofi.min.js?

**Comment by damienmcd** [comment]
I've just downloaded the latest release from GitHub and am prepending ofi.min.js and it seems to be working fine now.
I'm not sure what version we had previously as it was added by one of our other devs.
This issue can be closed. Thanks for your help on this.

**Comment by ugrupp** [comment]
confirmed, upgrading from 2.5.3 to 3.1.0 resolved the issue for me.
