### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by JonGarbayo** [bfred-it/object-fit-images#65]
Hi,

Could you please add the version number of your package in the header comment of the dist files?
I could be easier to update in a website ;)

Thanks for reading.
Jon

**Comment by fregante** [comment]
How do you update the file? Do you download it from GitHub? How would the version number in the file make it easy to update it?

**Comment by JonGarbayo** [comment]
That's it: I download and install it manually from GitHub.
I work in a web agency which doesn't deal with projects using NPM, so I don't really have the choice.

Sometimes, as I have to update some things in some "old" websites (just a few months old, lol), I also check some JS packages and libraries updates.

So yes, having the version number directly in the header comments can speed this kind of process, and I am sure that I am not the only one who do this kind of tasks :)

**Comment by fregante** [comment]
Understandable. I'll add a version
