### ISSUE TITLE
Correct escaping of the url in background-image

### ISSUE THREAD

**Issue by redneb** [bfred-it/object-fit-images#69]
According to the [CSS level 3 specification](https://www.w3.org/TR/css3-values/#urls):

> Note: The special parsing rules for the legacy quotation-mark–less <url> syntax means that parentheses, whitespace characters, single quotes (') and double quotes (") appearing in a URL must be escaped with a backslash, e.g. `url(open\(parens)`, `url(close\)parens)`. Depending on the type of URL, it might also be possible to write these characters as URL-escapes (e.g. `url(open%28parens)` or `url(close%29parens)`) as described in [URL]. Alternately, the URL can be quoted as a string, in which case only newlines and the character used to quote the string need to be escaped.

The current implementation in `object-fit-images` opts for quotation-mark–less syntax, but it only escapes the parentheses. It also uses the `replace` method of strings with a string the first argument, which will replace only the first occurrence. I propose to switch to the quotation-mark syntax which has simpler escaping rules and use a global regex to ensure that all characters are escaped. So something like the following should work:

    (ofi.img.currentSrc || ofi.img.src).replace(/(["\\])/g,"\\$1").replace(/\n/g,"\\n")

I'd be happy to prepare a pull request if it makes it easier for you, provided of course that you agree with the proposed change.

**Comment by fregante** [comment]
Excellent! Please do send a PR. Feel free to extract this `.replace()` sequence into its own function

Would it be easier to use `url('${.......}')` (notice the `'`) than adding `"` to the regex?

Also, why would `.replace(/\n/g,"\\n")` be necessary?

**Comment by redneb** [comment]
Hi, sorry for the late response.

Your commit (5c053186b1732f48371cae51a6a80519075ad7f1) improves the situation but does not address all corner cases. Specifically, it will not work if the file contains a backslash `\` (which is used for escaping special characters in strings, so it's a special character itself and has to be escaped) or a line break (which of course does not appear in filenames very frequently).

Here are some references to the relevant parts from the specification of the CSS lexer: a [url-token](https://www.w3.org/TR/css-syntax-3/#url-token-diagram) contains a [string-token](https://www.w3.org/TR/css-syntax-3/#string-token-diagram) which is a quoted sequence of literal characters (which cannot be `\`, newline, or the quoting character) or [escape](https://www.w3.org/TR/css-syntax-3/#escape-diagram)s.

**Comment by fregante** [comment]
Please provide an example CodePen with the right HTML. I assume that what we get from `img.src` is already somewhat encoded and it's not just random strings

**Comment by redneb** [comment]
You are right, `img.src` returns a full url so all special characters will most likely be taken care of. So your current solution should be fine for this case.
