### ISSUE TITLE
Not working with webpack?

### ISSUE THREAD

**Issue by MattFromGer** [bfred-it/object-fit-images#71]
When trying to pack the module with webpack, I get the following output:
```
[...]
(function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/*! npm.im/object-fit-images 3.1.3 */
var OFI = 'bfred-it:object-fit-images';
var propRegex = /(object-fit|object-position)\s*:\s*([-\w\s%]+)/g;
[...]
```
Meaning, webpack cuts off the global variable 'objectFitImages', thus I cannot get it to work.

**Comment by fregante** [comment]
When you use webpack you don't have global variables. 

# Webpack 1

Use `require` in your entry file:

```JavaScript
var objectFitImages = require('object-fit-images');
objectFitImages('img');
```

# Webpack 2

Use `import` in your entry file:

```JavaScript
import objectFitImages from 'object-fit-images';
objectFitImages('img');
```

**Comment by MattFromGer** [comment]
Ah, I see, thank you!

**Comment by MattyBalaam** [comment]
I can't get this to work either. I'm using WebPack 2.3.3

Using the code specified I get:

TypeError: objectFitImages is not a function

If I try a console log on that var I get `Object {__esModule: true, default: function}`

![image](https://cloud.githubusercontent.com/assets/1246923/25008652/466074d4-205c-11e7-967d-fc7c41d55933.png)

I have included what another require looks like

**Comment by MattyBalaam** [comment]
@bfred-it the only way I have been able to get this to work as expected is to use  

`const objectFitImages = require('object-fit-images').default`

**Comment by fregante** [comment]
Thanks for the followup!

It looks like webpack 2 picks up the ES module version even with `require`. I updated my first comment and I'm reopening this in case anyone else needs it.

**Comment by fregante** [comment]
🎉 If you use `object-fit-images` version 3.2.0, you can use either `require` or `import` without any issues in webpack 2

```sh
# run this to get the latest ofi version
npm update object-fit-images --save
```
