### ISSUE TITLE
Comparison table is not rendered properly

### ISSUE THREAD

**Issue by ImBobby** [bfred-it/object-fit-images#74]
<img width="947" alt="screen shot 2017-04-10 at 8 32 09 am" src="https://cloud.githubusercontent.com/assets/2084193/24842976/62a12efe-1dc8-11e7-8d7f-3205ad217a9c.png">

[This commit](https://github.com/bfred-it/object-fit-images/commit/e18ce7366199803dee1aebb918b817f7b1b70fae) might be the cause.

**Comment by fregante** [comment]
Thanks for the issue!

The cause is GitHub changing their markdown parser, unfortunately. I was hoping for them to catch up and fix it...

**Comment by fregante** [comment]
Fixed
