### ISSUE TITLE
padding not working after objectFitImages() used

### ISSUE THREAD

**Issue by 0x5e** [bfred-it/object-fit-images#76]
Hi, I'm trying to use `object-fit-images` in a vue project. After using `objectFitImages()`, `object-position: left;` works fine, but `padding: 2vw;` seems not working.

Here's the code & imgs:

```
<img class="btn" id="back-btn" src="../assets/tool.svg" v-on:click="backward" />
<img class="btn" id="done-btn" src="../assets/tool.svg" v-on:click="next" />
<img class="btn" id="forward-btn" src="../assets/tool.svg" v-on:click="forward" />
```

```
.btn {
  width: 10vw;
  height: 10vw;
  padding: 2vw;
  background: rgba(0, 0, 0, 0.1);

  position: fixed;
  top: 5vw;

  object-fit: cover;
}
#back-btn {
  left: 15vw;
  object-position: left;
  font-family: 'object-fit: cover; object-position: left;'
}
#done-btn {
  left: 45vw;
  object-position: center;
  font-family: 'object-fit: cover; object-position: center;'
}
#forward-btn {
  right: 15vw;
  object-position: right;
  font-family: 'object-fit: cover; object-position: right;'
}
```

tool.svg:
![image](https://cloud.githubusercontent.com/assets/5144674/25339029/e0e730da-2933-11e7-8323-e176b0d22b32.png)

before:
![ios9 3 3_before](https://cloud.githubusercontent.com/assets/5144674/25339074/0843dc32-2934-11e7-9c69-69e2150055f4.PNG)

after:
![ios9 3 3_after](https://cloud.githubusercontent.com/assets/5144674/25339124/3b25d3a8-2934-11e7-91fb-c1980778f6c1.PNG)

user-agent:
Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_3 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G34 Safari/601.1

**Comment by fregante** [comment]
Wow, I didn't know `img` can have padding.

I think you will have to add: 

```css
.btn {
  background-clip: content-box;
}

**Comment by 0x5e** [comment]
Thanks for reply, it's not working, .btn size became smaller, but content still big.


![img_4774](https://cloud.githubusercontent.com/assets/5144674/25370479/a96fcb28-29bd-11e7-93a4-b0fb2730cdcf.PNG)

￼

**Comment by fregante** [comment]
This should work

```css
.btn {
  background-origin: content-box;
}
```

Either way you should use `background-image` for sprites (or other [svg-specific spriting methods](https://github.com/jkphl/svg-sprite)), there's no need for `object-fit`
