### ISSUE TITLE
ie/edge bug

### ISSUE THREAD

**Issue by dartess** [bfred-it/object-fit-images#77]
Hello! I encountered an error in IE / Enge browsers.

If you do not pass the selector, by default images will be selected using the method `document.querySelectorAll('img')`. The problem is that, for historical reasons, the `image` tag in some browsers is an alias for the tag `img` (https://jakearchibald.com/2013/having-fun-with-image/), and at present this tag is also used as part of the `svg` specification. This leads to the fact that the browser tries to apply not only to the tag `img`, but also to the `image` tags located inside the inline `svg`. Since such elements do not have integer `width` and `height` properties, the script drops when you try to call `new Image(el.width, el.height)` on line 94.

There are probably many ways to solve the problem. I would suggest deleting line 184 `imgs = imgs || 'img';` and if the selector is not passed at all, select it by tag, not by selector.

```
if (!imgs) {
    imgs = document.getElementsByTagName('img');
} else if (typeof imgs === 'string') {
    imgs = document.querySelectorAll(imgs);
} else if (!('length' in imgs)) {
    imgs = [imgs];
}
```

Since I'm not sure if this is the best solution, I did not make a pull request.

**Comment by fregante** [comment]
That looks like a good solution! Feel free to submit a PR. If you're busy I'll do it myself next week.

**Comment by dartess** [comment]
https://github.com/bfred-it/object-fit-images/pull/78

**Comment by fregante** [comment]
Thank you! Now on 3.2.2
