### ISSUE TITLE
Lazyload support

### ISSUE THREAD

**Issue by superjunky** [bfred-it/object-fit-images#80]
It looks like ofi interferes with Lazyload functionality.

Is there a way to solve this?

**Comment by fregante** [comment]
What lazy load solution are you using?

**Comment by superjunky** [comment]
A LazyLoad solution in WP-Rocket (cache module) http://docs.wp-rocket.me/article/278-common-issues-with-lazyload

One of the common issues they mention: JavaScripts that try to calculate spaces based on image size

I have seen the problem in IE 11 since I updated OFI to the recent version.

**Comment by fregante** [comment]
OFI doesn't set the image size, it just sets the `src`

What's the issue exactly? Can you show me the broken dom? Even better, can I see the site with the issue?

**Comment by superjunky** [comment]
Images are not visible when they enter the viewport.
I can see them load when I scroll down, but then immediately are hidden again.

You can see the effect on http://www.photosessions.nl/fotoshoot/koppels/romantische-fotoshoot-koppels/
Scroll down and look for the empty spaces in the long text element on the page. (In IE 11)
You can see a correct version of the page in Chrome, Safari, Firefox

**Comment by superjunky** [comment]
I see there is a `data-lazy-src` in there that gets removed.

**Comment by superjunky** [comment]
Along with a `data-lazy-srcset`.

Sry for the double post

**Comment by fregante** [comment]
Why are you using object-fit in the first place on a WordPress site? It's best that you load the correctly-sized image instead of something so big: http://www.photosessions.nl/wp/wp-content/uploads/2016/01/01-PhotoSessions-3-4-670x446@2x.jpg

**Comment by superjunky** [comment]
Yes that's true, and also not the point of the topic. There are more situations, but this was merely an easy example to point to.

Will it be possible to add support for the 'lazy-src' tags?

**Comment by fregante** [comment]
I looked into [the code of your plugin](http://www.photosessions.nl/wp/wp-content/plugins/wp-rocket/inc/front/js/lazyload.1.0.5.js) and I couldn't find a way to make it work automatically.

A solution I could think of is enabling OFI on the lazy images **after** they're loaded:

```js
// instead of your objectFitImages() call:
objectFitImages('img:not([data-lazy-src])'); // this will skip lazy images

$('[data-lazy-src]').one('lazybeforeunveil', function (e) {
  $(e.target).one('load', function () {
    objectFitImages(e.target);
  })
});
```
