### ISSUE TITLE
Using with WordPress

### ISSUE THREAD

**Issue by ericleonardo** [bfred-it/object-fit-images#81]
Hi! I'm having trouble trying to use Object Fit Images within WordPress theme.
This is what I've done:
1. Put Ofi.js file in the theme "JS" folder;
2. Put `<script>objectFitImages();</script>` on header file;
3. Inserted `object-fit:contain;font-family: 'object-fit: contain;';` line as img property on theme CSS;
4. Put all preprocessors in the theme CSS folder.

Several months ago I was able to use it on the same theme.
See it working: Hotsales.com.br (Calvin Klein pants, Xbox One image)

But now I'm trying to update the theme and can't put it to work.
See it not working: novosite.hotsales.com.br

Please, can you help me?
Thank you very much! Eric

**Comment by fregante** [comment]
This looks like a support question. Please ask on a support forum. There are a lot of active Facebook Groups nowadays :)

**Comment by ericleonardo** [comment]
I've just got it to work!
Had to change a true to false on theme functions where defines add_image_size.
Thanks
