### ISSUE TITLE
module.export feature

### ISSUE THREAD

**Issue by rus-yurchenko** [bfred-it/object-fit-images#82]
Hi there, found a bug when I bundle and minify my scripts. If I don't minify my code all works good 
 but after minify lib doesn't work and shows in console Uncaught ReferenceError: objectFitImages is not defined.  I think it's because you are using function expression but not something like module structure.

**Comment by fregante** [comment]
What are you using to minify it? This is likely not an issue with ofi itself, but perhaps I can help you

**Comment by rus-yurchenko** [comment]
@bfred-it I'm using gulp and gulp-uglify with default config for this. Didn't have the same issues with other libs.

**Comment by fregante** [comment]
What's the `gulp-uglify` version?

Post your gulpfile

**Comment by rus-yurchenko** [comment]
The latest 3.0.0. But it minify some strange. I see a variable objectFitImages in your minified version but in my I only have this variable on function call.

**Comment by fregante** [comment]
What do you use to bundle your scripts? Are you concatenating them? I can't help you without your config

**Comment by rus-yurchenko** [comment]
Please take a look on this [link](https://github.com/roots/sage/blob/8.5.1/gulpfile.js#L133).

**Comment by fregante** [comment]
Can you post the resulting JS file?

**Comment by rus-yurchenko** [comment]
Sure, [here](https://gist.github.com/RuslanYurchenko/9ac0076387661987a5c8f88abb3d77c3)

**Comment by fregante** [comment]
I see the issue, you're calling `objectFitImages` in the wrong way:

```js
$(document).ready(objectFitImages());
```

Refer to point 3 here:
https://github.com/bfred-it/object-fit-images#usage

**Comment by rus-yurchenko** [comment]
I tried also $(function () { objectFitImages() }) and still not works.

**Comment by fregante** [comment]
Ah true, there's something wrong with your build since OFI is not included at all (search for `fit` in the JS file). This is unrelated to OFI completely, you might have to ask on a forum or StackOverflow.

**Comment by rus-yurchenko** [comment]
ok, will look on it. Thanks for help!

**Comment by kapouer** [comment]
Nowadays bundlers rely on some umd pattern, which is not compatible with a mere
`var objectFitImage = ...`
If you're not keen on using modules, and since this module is designed to be used on browser it should attach its main function to window (or to HTMLImageElement ?).
