### ISSUE TITLE
Problem with object-position in Internet Explorer 11 and Edge

### ISSUE THREAD

**Issue by Hypocrite** [bfred-it/object-fit-images#86]
We are using the latest version 3.2.3 of the script and it seems like Internet Explorer and Edge are not behaving the same way as for example Chrome.

We have set the CSS styles for images as:
object-fit: cover;
object-position: 50% 0;

The end result should be that the image is fitted to content and starts from the top of the content area.

This works fine in Chrome but in IE it starts in a different place.

Attached are screenshots from Chrome and IE. IE and Edge are the same when viewed.
![objectfit_chrome](https://user-images.githubusercontent.com/1395541/27433751-aab6f622-575e-11e7-804f-a0426bb92a8a.png)
![objectfit_ie](https://user-images.githubusercontent.com/1395541/27433753-aabc640e-575e-11e7-9ee0-d2bec506c52f.png)

Following styles seem to be applied in IE:
```<img style='background-position: center; background-image: url("http://192.168.99.55/sites/default/files/styles/full_width/public/collection/header/maxresdefault.jpg?itok=iXWYMX1z"); background-repeat: no-repeat; background-size: cover; background-origin: content-box;' alt="" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='1500' height='844'%3E%3C/svg%3E" data-ofi-src="http://192.168.99.55/sites/default/files/styles/full_width/public/collection/header/maxresdefault.jpg?itok=iXWYMX1z">```

**Comment by fregante** [comment]
What's your `font-family` setting? It's likely not set correctly

**Comment by Hypocrite** [comment]
Thanks. I think I found the problem now.

**Comment by gijsroge** [comment]
@Hypocrite Please share your solution.
