### ISSUE TITLE
object-fit on IE breaks saving images

### ISSUE THREAD

**Issue by heyokaysaturday** [bfred-it/object-fit-images#87]
Hey there :)

On images with the object-fit applied to them on IE browsers cannot be saved to desktop anymore (it attempts to save an untitled.png instead)

![capture](https://user-images.githubusercontent.com/13955454/27938666-d7cd2208-6302-11e7-85ce-4ed43e9ea60e.PNG)

**Comment by fregante** [comment]
Yeah that's the downside of using OFI. If it's required then you'll have to use a different solution.

**Comment by heyokaysaturday** [comment]
No worries :) Thank you for responding.
