### ISSUE TITLE
"Uncaught TypeError: object_fit_images_1.default is not a function"

### ISSUE THREAD

**Issue by mallerie** [bfred-it/object-fit-images#88]
I am using webpack 2.

I have a component like the one below:

```
import * as React from 'react';
import * as PropTypes from 'prop-types';

import Slider from 'react-slick';
import objectFitImages from 'object-fit-images';

export class ImageComponent extends React.Component<any, any> {
  componentDidMount() {
    objectFitImages();
  }

  render() {
    let { src } = this.props;

    return (
      <img src={this.props.src} className={"carousel-img"} />
    );
  }
}
```

When I try to run objectFitImages(), I get an error saying, "Uncaught TypeError: object_fit_images_1.default is not a function." I get this error both in IE and Chrome. Can you explain why the function is not accessible?

![screen shot 2017-08-28 at 11 07 00 am](https://user-images.githubusercontent.com/16726365/29779624-155beab2-8be1-11e7-9a60-0448aa5cd840.png)

**Comment by fregante** [comment]
Are you using the latest version of OFI? (object-fit-images)

**Comment by mallerie** [comment]
Yep, just installed it a couple of days ago. I have version 3.2.3.

**Comment by fregante** [comment]
Try using `require` for now. I'll fix this at some point. I think they changed the behavior again. Can you post your webpack config?

**Comment by mallerie** [comment]
That did the trick. Thanks.

**Comment by fregante** [comment]
I think you have babel misconfigured because it works in webpack out of the box.

**Comment by mallerie** [comment]
Misconfigured how? I'm not getting any other errors related to Babel.

**Comment by fregante** [comment]
The error in the title of this issue was **because of** babel. You won't get errors directly from babel.

I think that your es2015/whatever preset is set to convert ES modules (`import`) but webpack already takes care of that. Maybe you need to set `{modules: false}` https://github.com/babel/babel-preset-env#modules

**Comment by fregante** [comment]
For example, can you try to pack only this file using your config?


```js
import OFI from "object-fit-images";
console.log(OFI);
```

Then post the resulting JS file and the webpack config here. I'm curious now because I can't replicate the bug even with webpack+babel.

**Comment by mallerie** [comment]
I figured it out. My mistake was how I was importing the package. I needed to use (for TypeScript):

`import * as objectFitImages from 'object-fit-images';`

Thank you for your timely responses and help.

**Comment by fregante** [comment]
That's still the wrong way though. `objectFitImages` is a single export/function. `import * as X` means "take all the exports and make an object named X". I suppose that also TypeScript is affecting the build, but without seeing the config I'm just guessing.

**Comment by fregante** [comment]
From what I see in the [TypeScript documentation](https://www.typescriptlang.org/docs/handbook/modules.html), it sounds the official way to import commonjs modules is `import OFI = require('object-fit-images')`

Trying it on https://www.typescriptlang.org/play/index.html, it looks like that's correct.

**Comment by mallerie** [comment]
Interesting. I have never seen that syntax for importing before. Thank you, I will read the documentation and make changes accordingly.

**Comment by diagramatics** [comment]
Just for future reference, I had the problem too and doing `import * as objectFitImages from 'object-fit-images'` does the trick.
