### ISSUE TITLE
Upgrade v2 to v3 changes

### ISSUE THREAD

**Issue by JimmyAppelt** [bfred-it/object-fit-images#89]
Hi guys, 

First of all thank for this great package!

Are you guys keeping some changelog or anything that document what kind of changes that could break when upgrading to v3 from v2 ? I couldn't find anything in specific, I might have looked over it somewhere.

From 2.5.6 to 3.2.3 in our case.

Thanks!

**Comment by fregante** [comment]
The changelog is half in changelog.md, half in GitHub releases.

Between v2 and v3 the API didn't change, but the underlying code changed a bit so I didn't want to risk breaking sites. Upgrading to v3 should be effortless.

**Comment by JimmyAppelt** [comment]
Thanks for your prompt response @bfred-it 

Have a great day!
