### ISSUE TITLE
Why scale-down mapped to contain?

### ISSUE THREAD

**Issue by ghost** [bfred-it/object-fit-images#9]
Hello

Why scale-down is only mapped to contain?

According to https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit:

> **scale-down**
>     The content is sized as if **none** or **contain** were specified, whichever would result in a smaller concrete object size.

Can you add the _none_ for _scale-down_?
Thank you.

**Comment by fregante** [comment]
Fixing it to follow the spec (and thus switching between none and contain) would mean having to calculate the image size at every resize. It's a bit costly but I'll consider it.

**Comment by ghost** [comment]
To begin, if this work only at the first display, it's good for me :)

**Comment by fregante** [comment]
Could you test this out and let me know how it works before I push it to npm?

**Comment by ghost** [comment]
Yeah :) For me, it works with IE 11 and Firefox 22. My little image is... little and my big image is resized. Thank you, good job!

**Comment by fregante** [comment]
Published to npm as 2.3.0
