### ISSUE TITLE
Internet Explorer Print

### ISSUE THREAD

**Issue by evanBracken** [bfred-it/object-fit-images#91]
Background images will not print in IE without the important rule (!important;) even if "Print Background Colors and Images" is selected. 

Quick fix is to add !important after the url.  

![image](https://user-images.githubusercontent.com/31745856/30183873-051a80da-93ea-11e7-9100-019ab13b2a4f.png)

**Comment by fregante** [comment]
Does that actually work? 😮

**Comment by evanBracken** [comment]
As far as I can see :) (screen capture from IE print preview)

![image](https://user-images.githubusercontent.com/31745856/30184125-e33c3b7e-93ea-11e7-9c01-25a03f109c84.png)

**Comment by fregante** [comment]
What IE and Windows version are you trying this from? I just tried adding `!important` to my `background-image` rule in IE11 on Win8.1 but nothing changed in the XPS printer.

**Comment by evanBracken** [comment]
IE 11.1593.14393.0 and Windows 10. 

And you've got "Print Background Colors and Images" checked? 

I just checked XPS printer, I was using a Canon, and it worked.

**Comment by fregante** [comment]
I'm not seeing that option at all:

<img width="474" alt="screen shot 2017-09-08 at 03 54 51" src="https://user-images.githubusercontent.com/1402241/30184815-7ab6d104-9449-11e7-84d8-55d49e8e62f9.png">
<img width="476" alt="screen shot 2017-09-08 at 03 54 43" src="https://user-images.githubusercontent.com/1402241/30184817-7aebe312-9449-11e7-8c95-1e96fffb35a6.png">

**Comment by fregante** [comment]
Ok I found it hidden in the Print _menu_.

I only had to enable it and the backgrounds appeared in the preview. I doubt that `!important` has any effect on it. `!important` only affects the CSS cascade, not any further behavior of the browser.

<img width="1042" alt="screen shot 2017-09-08 at 04 03 31" src="https://user-images.githubusercontent.com/1402241/30185236-d4111808-944a-11e7-97d3-c1c400660888.png">

**Comment by evanBracken** [comment]
Settings > Print > Page Setup

![image](https://user-images.githubusercontent.com/31745856/30186038-e047fba4-93f1-11e7-8c3e-9fa330840e9e.png)

And the only image that wasn't showing up for me was the one I was using with this library and !important fixed it, not sure why. I know that in Chrome, background colors won't show up unless !important is used, might be something similar. 

Thanks for checking.
