### ISSUE TITLE
IE/Edge functionality

### ISSUE THREAD

**Issue by BrianBenninger** [bfred-it/object-fit-images#93]
I have tested this on IE 11.540.15063.0 and Edge 40.15063.0.0 and in both instances object-fit/object-position does not work. Whether I test my own sites or your demo page I am receiving no functionality.

**Comment by BrianBenninger** [comment]
Wanted to include an image of what I'm seeing in Edge.
![object-fit-error](https://user-images.githubusercontent.com/29063944/30227684-7e713f0a-94a8-11e7-9d58-ba4d50cfcbe6.PNG)
Thank you.

**Comment by fregante** [comment]
You have to click the Apply Fix button in the demo. I tested it just yesterday in IE11

**Comment by fregante** [comment]
On your own site, make sure you're following the instructions (e.g. using the `font-family` trick)

**Comment by BrianBenninger** [comment]
Thank you, that does fix the demo page. Also I found that I was calling the function incorrectly, all is well now. Thank you for you quick response and sorry for the false alarm.

**Comment by fregante** [comment]
No worries! Thanks for opening an issue regarding a possible bug :)
