### ISSUE TITLE
Uses src when image has srcset

### ISSUE THREAD

**Issue by bradroberts** [bfred-it/object-fit-images#98]
I can't seem to get it working with srcset. I'm testing IE 11, and it uses the image src rather than the srcset images. I may be overlooking something because I haven't found anyone other posts about this. Any help is greatly appreciated.

Please check out this [JSFiddle](https://jsfiddle.net/4bvd2wum/). srcset images are green. The src image is red.

**Comment by fregante** [comment]
Thanks for providing a JSFiddle! You're missing a `;` after the `font-family` line. Notice how `position` has the wrong color.

<img width="282" alt="screen shot 2017-11-07 at 01 25 59" src="https://user-images.githubusercontent.com/1402241/32454597-a795f4b2-c35a-11e7-8901-32031f525819.png">

**Comment by bradroberts** [comment]
I copied it from the example on the readme! LOL :)  I fixed that, but it's still using the src rather than the srcset in IE 11.

Thank you for the quick reply.

**Comment by bradroberts** [comment]
Any thoughts on what I might be doing wrong? I've tried everything I can think of and even looked through the source, but I can't figure it out. I appreciate your time.

It should be showing a green image (srcset), but in IE 11 it shows the red image from src. https://jsfiddle.net/4bvd2wum/3/

**Comment by bradroberts** [comment]
Ok. I'm a moron. Object-fit-images is doing its job just fine - fitting the image to its container.

My issue is that IE does not support srcset. Browsers that do support srcset, set a `currentSrc` property on the image after deciding which image to use. Object-fit-images uses the currentSrc property (falling back to src) to determine the image to use.

So, if you're using srcset you need an additional polyfill - [Picturefill](https://github.com/scottjehl/picturefill). If I had read the documentation thoroughly I would have caught this. Object-fit-images works with Picturefill to use the desired image from srcset.

[Working Fiddle](https://jsfiddle.net/4bvd2wum/5/)

@bfred-it Feel free to correct anything I've said that's incorrect. Thank you again for your help and for your work on this script!
