### ISSUE TITLE
<picture> element in Edge

### ISSUE THREAD

**Issue by montik** [bfred-it/object-fit-images#99]
I have a picture element

```
<picture>
<source srcset="img.jpg" media="(min-width: 1200px)">
<source srcset="img.jpg" media="(min-width: 900px)">
<img src="img.jpg">
</picture>
```

I have this picture displayed with _object-fit: cover_. In IE/Edge the polyfill works, the img element gets the inline style. Though Edge ignores it and renders the picture from sourceset, "squeezed".

**Comment by fregante** [comment]
Picture is not supported #3
